# Base URL of the site to crawl
base_url: "https://www.google.com/"   #  <------------Add your base URL here


# Optional buttons to click on page load
buttons:
  continue_button_name: "Continue"

# Routes to check
routes:
 - /
 - /advanced_search
 - /imghp
 - /intl/en_in/ads/
 - /preferences
 - /services/
 - /setprefs

 

# Browser type to use: chromium, firefox, webkit
browser: chromium

# Page timeout in milliseconds
timeout: 60000

# Maximum number of pages to crawl
max_pages: 1000

# Enable crawling all links found on pages
enable_full_crawl: True

# Domains or URL patterns to skip while crawling
skip_domains:
  - facebook.com
  - linkedin.com
  - instagram.com
  - twitter.com
  - youtube.com
  - "mailto:"
  - "tel:"

# Report file to save broken links
report_file: "reports/broken_links_report.xlsx"

# Viewport settings
# Viewports to test
viewports:
  - { width: 1920, height: 1080, name: "desktop" }
  - { width: 820, height: 1180, name: "tablet" }
  - { width: 390, height: 844, name: "mobile" }

